### ISSUE TITLE
Topological Order

### ISSUE THREAD

**Issue by xijohnny** [francescomontagna/causally#11]
Hi Francesco, 

Thanks for releasing this package, I've found it to be very useful for benchmarking! I think however there is a bug in the topological order function, which can cause some weird behaviour when sampling from the SCM.

https://github.com/francescomontagna/causally/blob/bbe0c2fce939cf3f784abfd09cee0f7a991641e1/causally/utils/graph.py#L33-L53

When iterating through, the nodes marked as leaf are not removed from the children set of the remaining nodes. The function hence returns a sort according to increasing number of children, which is not always a topological sort. Here is an example of a chain graph, 0->1->2->3->4:

```python
>>> from causally.utils import graph as graph_utils 
>>> import numpy as np
>>> adj = np.triu(np.tril(np.ones((5,5)),-1),-1).T
>>> print(adj)
[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]
>>> print(graph_utils.topological_order(adj))
[3, 2, 1, 0, 4]
````
The function correctly identifies 4 as a leaf, but since all other nodes have exactly one child, `np.argmin` breaks ties by selecting the smallest index, and so 0 is identified as the next leaf. A small fix in l46 can solve the problem:
```python
children_per_node = (
            adjacency.sum(axis=1) + mask - adjacency[:,order].sum(axis=1)
        )
```
which removes children that are already in the order.
```
>>> print(graph_utils.topological_order_(adj))
[0, 1, 2, 3, 4]
```

**Comment by francescomontagna** [comment]
Hi Quanhan,

I'm glad you're finding this work useful. Sorry for the delay in the reply.  Many thanks for pointing out this error, I really appreciate that. I will fix it ASAP and keep you posted on this issue! Also, feel free to open a PR in case you find any other issue, contributions are  certainly welcome :)
