### ISSUE TITLE
Challenging assumptions

### ISSUE THREAD

**Issue by felixleopoldo** [francescomontagna/causally#5]
Hi Francesco,

This seems like a nice library! I am trying to run the Challenging Assumptions example from the docs but get some errors. I know the docs is under development but it would be nice if you would update at least the examples parts so one can try it. I will see if I can add some parts of this to [Benchpress](https://benchpressdocs.readthedocs.io).

**Comment by francescomontagna** [comment]
Hi Felix, 

Thanks for your interest in my library! Sorry to hear that, can you please let me know where the error happens and what is the message? 
Anyway, I plan to add additional examples to the documentation in the near future, I will keep you updated here

**Comment by felixleopoldo** [comment]
Sounds good!
First, the context library seems to have changed place, see the screenshot. But when I fix that, there are new errors.
<img width="1612" alt="Skärmavbild 2023-11-28 kl  10 22 37 (2)" src="https://github.com/francescomontagna/causally/assets/34372003/4e6b4333-1b89-465a-abc5-c162db239f2c">

**Comment by francescomontagna** [comment]
Hi Felix! Thank you for your patience, I am back. I should have fixed the issues you have been encountering,  and changes have been merged in the main. Also, I reviewed the documentation, aiming for better clarity. Hopefully that helps. I haven't had time for writing notebooks, hoepefully I'll be able to do that in the upcoming few weeks. 

You can test the changes with this code snippet (which you can find also under `Usage` in the documentation):
```
import causally.scm.scm as scm
import causally.graph.random_graph as rg
import causally.scm.noise as noise
import causally.scm.causal_mechanism as cm
from causally.scm.context import SCMContext
import numpy as np
import random

SEED = 42
np.random.seed(SEED)
random.seed(42)

# Erdos-Renyi graph generator
graph_generator = rg.ErdosRenyi(num_nodes=10, expected_degree=2)

# Generator of the noise terms
noise_generator = noise.MLPNoise()

# Nonlinear causal mechanisms (parametrized with a random neural network)
causal_mechanism = cm.NeuralNetMechanism()

# Context for the assumptions
context = SCMContext()

# Make assumption: confounded model
context.confounded_model(p_confounder=0.1)

# Make assumption: unfaithful model
context.unfaithful_model(p_unfaithful=1)

# Generate the data
model = scm.AdditiveNoiseModel(
        num_samples=1000,
        graph_generator=graph_generator,
        noise_generator=noise_generator,
        causal_mechanism=causal_mechanism,
        scm_context=context,
        seed=42
)

# Sample from the model
dataset, groundtruth = model.sample()
```

Let me know if you have any problem, or general feedback: I'd be happy to hear from you and to bring the discussion further.

**Comment by felixleopoldo** [comment]
Thanks Francesco, I'll try this!
