### ISSUE TITLE
Question in scm_property.py Line 290

### ISSUE THREAD

**Issue by huiyang-yi** [francescomontagna/causally#8]
Hi Francesco,

I have questions about the code in line 290 of scm_property.py, and I think that X[t] += linear_coeffs[k] * X[t - k] should be replaced with X[t] += linear_coeffs[k] * X[t - k - 1], which feels more reasonable. Looking forward to your reply.

https://github.com/francescomontagna/causally/blob/18bce4ca19c96dbeb402d28c95829373b51d4ad3/causally/scm/scm_property.py#L290

**Comment by francescomontagna** [comment]
Hi @huiyang-yi, you are right! thanks so much for pointing that out. I will fix it asap and keep you posted here.
